### PR TITLE
fix: react defaultProps warning

### LINKED ISSUE #39538: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
Screenshot 2022-12-13 alle 14 33 31
### Reproduction link

[https://ant.design/components/drawer](https://ant.design/components/drawer)

### Steps to reproduce

Have a simple drawer which open on button click, 

### What is expected?

No error inside console

### What is actually happening?

Error console: https://ibb.co/4TNh5dK

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18 |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by chunsch**
fix https://github.com/ant-design/ant-design/issues/39538

https://github.com/facebook/react/pull/16210

### CODE REVIEW

File: src/Drawer.tsx [hunk 1]
```diff
@@ -17,7 +17,25 @@ export interface DrawerProps
...
+  width: 378,
+  mask: true,
+  maskClosable: true,
+};
+
+const Drawer: React.FC<DrawerProps> = drawerProps => {
+  const props = {
+    ...defaultProps,
+    ...drawerProps,
+  };
```
Comment (MadCcc) [inline src/Drawer.tsx:38]: 用解构写法赋默认值吧

**Review by MadCcc — APPROVED** [review]

**Comment by yoyo837** [comment]
是不是没发 minor 整挂了 😂
